version: '3.8'

services:
  app-zeeven:
    container_name: app-zeeven
    # The official v2 Traefik docker image
    image: simachille/app-zeeven:latest
    restart: always
    ports:
      # The HTTP port
      - "82:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-zeeven.rule=Headers(`X-Host`, `app.zeeven.chillo.fr`)"
      - "traefik.docker.network=applications-network"
      - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*" 
      - "traefik.http.routers.service.middlewares=serviceheaders"

    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network